import { DEFAULT_PROBE_PROMPT } from "../runtime/probe.js";

export function probePage(csrfToken: string, nonce: string): string {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="g0-csrf" content="${csrfToken}"><link rel="icon" href="data:,"><title>Pivloom · G0 维护验证</title>
<style nonce="${nonce}">
*{box-sizing:border-box}body{margin:0;background:#f5f5f1;color:#27312b;font:15px/1.5 system-ui,sans-serif}main{max-width:1320px;margin:auto;padding:24px}h1{font-size:25px;margin:0}h2{font-size:18px;margin:0 0 14px}p{margin:8px 0;color:#586259}.grid{display:grid;grid-template-columns:minmax(290px,380px) minmax(0,1fr);gap:20px;margin-top:22px}.card{padding:22px;background:white;border:1px solid #dde2db;border-radius:16px;min-width:0}label{display:block;font-weight:600;margin-top:12px}input,select,textarea,button{font:inherit}input,select,textarea{display:block;width:100%;border:1px solid #c4cec3;border-radius:8px;background:#fff;color:#243128;padding:9px 11px;margin-top:5px}textarea{min-height:132px;resize:vertical}button{border:1px solid #bac6b7;border-radius:9px;padding:9px 13px;cursor:pointer;background:#fff;color:#27382c}button.primary{background:#2e563e;color:white;border-color:#2e563e}button:disabled{opacity:.45;cursor:default}button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:3px solid #a0ba81;outline-offset:2px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.note{font-size:13px}.status{font-weight:650;margin-bottom:10px}.events{max-height:230px;overflow:auto;font:12px/1.7 ui-monospace,monospace;padding-left:22px;overflow-wrap:anywhere}.checks{font-size:13px}.preview-wrap{margin-top:20px;background:#e9ede7;border-radius:12px;padding:8px;overflow:auto}iframe{display:block;width:100%;height:580px;border:0;background:white;border-radius:8px;margin:auto}iframe.mobile{width:min(390px,100%)}pre{white-space:pre-wrap;font-size:11px;overflow-wrap:anywhere}.hidden{display:none}[role=alert]{color:#a12e2e;white-space:pre-wrap}@media(max-width:820px){main{padding:14px}.grid{grid-template-columns:1fr}.card{padding:16px}iframe{height:560px}}
</style></head><body><main><h1>G0 维护验证</h1><p>输入小需求，观察真实 Pi 远程工具、构建与 Chrome 检查，再独立操作生成的应用。</p><p class="note">仅本机使用。模型 Key 只用于本次请求，不保存到文件或页面存储；正式工作台尚未串联。</p><div class="grid"><section class="card"><h2>本次任务</h2><form id="run-form" autocomplete="off"><label for="prompt">需求</label><textarea id="prompt" name="prompt" required maxlength="4000">${DEFAULT_PROBE_PROMPT}</textarea><p class="note">此探针保留“记录”文本框和“添加”按钮，便于独立行为验证。</p><label for="api">API 协议</label><select id="api" name="api"><option value="openai-completions">OpenAI Chat Completions</option value="anthropic-messages">Anthropic Messages</option></select><label for="provider">Provider 名称</label><input id="provider" name="provider" required value="pivloom-ark"><label for="baseUrl">Base URL</label><input id="baseUrl" name="baseUrl" type="url" required value="https://ark.cn-beijing.volces.com/api/coding/v3"><label for="modelId">模型 ID</label><input id="modelId" name="modelId" required value="glm-5.3-flash"><label for="apiKey">本次模型 Key</label><input id="apiKey" name="apiKey" type="password" required autocomplete="new-password" spellcheck="false"><div class="actions"><button class="primary" id="start" type="submit">开始真实验证</button><button id="cancel" type="button" disabled>取消任务</button><button id="cleanup" type="button" disabled>清理沙箱</button></div></form><p id="error" role="alert"></p></section><section class="card"><h2>执行与预览</h2><p id="status" class="status" role="status" aria-live="polite">等待输入</p><p id="cleanup-state" class="note"></p><ol id="events" class="events" aria-label="实际执行阶段"></ol><div id="checks" class="checks"></div><div class="actions"><button id="width" type="button">切换 390px 预览</button></div><div id="preview-wrap" class="preview-wrap hidden"><iframe id="preview" title="真实生成的应用" sandbox="allow-scripts allow-forms allow-same-origin"></iframe></div><details><summary>本次验证标识</summary><pre id="identity">尚无任务</pre></details></section></div></main>
<script nonce="${nonce}">
const csrf=${JSON.stringify(csrfToken)};let runId;let polling=false;let renderedPreview;
const byId=id=>document.getElementById(id);const error=byId('error');
async function request(path,method='GET',body){const headers={'X-G0-CSRF':csrf};if(body)headers['Content-Type']='application/json';const response=await fetch(path,{method,headers,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error?.message||'维护入口请求失败');return data;}
function render(data){runId=data.id;const active=['running','cancelling'].includes(data.status);const blocked=active||['ready','cleanup_pending'].includes(data.status);byId('start').disabled=blocked;byId('cancel').disabled=!active||data.status==='cancelling';byId('cleanup').disabled=active||!data.result?.cleanup?.sandboxId||data.result.cleanup.state==='confirmed';byId('status').textContent=data.message||data.status;byId('cleanup-state').textContent='沙箱清理：'+(data.result?.cleanup?.state||'任务进行中');const list=byId('events');list.replaceChildren(...data.events.map(event=>{const li=document.createElement('li');li.textContent=new Date(event.at).toLocaleTimeString()+' '+event.message+(event.success===false?'（未成功）':'');return li;}));list.scrollTop=list.scrollHeight;const result=data.result;byId('checks').replaceChildren(...(result?.evidence?.checks||[]).map(check=>{const p=document.createElement('p');p.textContent=check.status+' · '+check.name+'：'+check.detail;return p;}));byId('identity').textContent=JSON.stringify({bootId:data.bootId,maintenanceRunId:data.id,runId:result?.runId,preview:result?.preview,cleanup:result?.cleanup},null,2);if(result?.error)error.textContent=result.error.code+'：'+result.error.message;const url=data.status==='ready'?result?.preview?.url:undefined;if(url&&url!==renderedPreview){byId('preview').src=url;renderedPreview=url;byId('preview-wrap').classList.remove('hidden');}if(data.status==='cleaned'||data.status==='cancelled'){byId('preview').removeAttribute('src');byId('preview-wrap').classList.add('hidden');renderedPreview=undefined;}return active;}
async function poll(){if(polling||!runId)return;polling=true;try{let active=true;while(active){const data=await request('/runs/'+runId);active=render(data);if(active)await new Promise(resolve=>setTimeout(resolve,900));}}catch(e){error.textContent=e.message;}finally{polling=false;}}
byId('run-form').addEventListener('submit',async event=>{event.preventDefault();error.textContent='';byId('start').disabled=true;const data=new FormData(event.currentTarget);const body={prompt:data.get('prompt'),model:{provider:data.get('provider'),api:data.get('api'),baseUrl:data.get('baseUrl'),id:data.get('modelId'),apiKey:data.get('apiKey'),maxTokens:4096}};byId('apiKey').value='';try{const accepted=await request('/runs','POST',body);body.model.apiKey='';runId=accepted.id;byId('events').replaceChildren();byId('preview').removeAttribute('src');byId('preview-wrap').classList.add('hidden');renderedPreview=undefined;void poll();}catch(e){body.model.apiKey='';error.textContent=e.message;byId('start').disabled=false;}});
byId('cancel').addEventListener('click',async()=>{error.textContent='';try{render(await request('/runs/'+runId+'/cancel','POST'));void poll();}catch(e){error.textContent=e.message;}});
byId('cleanup').addEventListener('click',async()=>{error.textContent='';byId('cleanup').disabled=true;try{render(await request('/runs/'+runId,'DELETE'));}catch(e){error.textContent=e.message;byId('cleanup').disabled=false;}});
byId('width').addEventListener('click',()=>{const mobile=byId('preview').classList.toggle('mobile');byId('width').textContent=mobile?'恢复完整宽度':'切换 390px 预览';});
request('/runs/current').then(data=>{render(data);void poll();}).catch(()=>{});
</script></body></html>`;
}
